displayName=BA Healer Order
author=Underdog
support=
description=Displays Barbarian Assault Penance Healer spawn order and, optionally, food counts.
tags=barbarian assault,ba,healer,penance,barb assault
plugins=com.bahealerorder.BaHealerOrderPlugin
version=1.0.2
build=standard