displayName=BA Utilities
author=Underdog
support=https://github.com/tcourter1/ba-healer-order
description=Displays various utilities for high-level Barbarian Assault gameplay.
tags=barbarian assault,ba,healer,penance,barb assault
plugins=com.bahealerorder.BaHealerOrderPlugin
version=2.1.1
build=standard